language: java

jdk:
  - oraclejdk8

matrix:
  include:
  - env: PROFILE=ci
  - env: PROFILE=springldap-next
  allow_failures:
  - env: PROFILE=springldap-next

addons:
  apt:
    packages:
    - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

install: true

script: "mvn clean dependency:list test -P${PROFILE} -Dsort"
